### ISSUE TITLE
Installation failed: no matching package named `chisel` found

### ISSUE THREAD

**Issue by clement-ux** [max-taylor/Chisel-GPT#1]
Hi, I've cloned the repo, and run `cargo run`, but I get the following issue:
error: no matching package named `chisel` found
location searched: https://github.com/foundry-rs/foundry.git#388c3c0a
required by package `ChiselGPT v0.1.0 (/Users/--/Chisel-GPT)`

But when I run just `chisel`, I get the classical chisel environnement on terminal.

Maybe I've done something wrong on my side?
Thanks a lot for your amazing work!

**Comment by max-taylor** [comment]
Hi @clement-ux, Thanks for the feedback!
That's strange, I set this up on a separate machine and didn't run into your issue.
Maybe send a dump of all the logs and I can take a better look

**Comment by iconofsin** [comment]
Same issue. `chisel` runs, but `cargo run` for chisel-gpt produces the same error.

**Comment by max-taylor** [comment]
Do you have ssh-agent authentication setup? [Here is a link to setting that up if you need](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

I think that is required because some dependencies are git dependencies and I think they only allow SSH auth.

Sorry I’ll can update the Readme if that’s the case

**Comment by iconofsin** [comment]
Followed the instructions, set it up, still the same error.

**Comment by max-taylor** [comment]
Did you also complete the adding your keys to the [SSH-agent steps](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent)?

Can you paste your entire error output, if this doesn't fix it?

Sorry about this surprised it's not more straight-forward.

**Comment by iconofsin** [comment]
Yes, indeed, I followed through with all of it.
```
% cargo run
error: no matching package named `chisel` found
location searched: https://github.com/foundry-rs/foundry.git#388c3c0a
required by package `ChiselGPT v0.1.0 (/Users/zerno/Downloads/Chisel-GPT)`
```

**Comment by max-taylor** [comment]
Very strange. Just updated the dependencies to pin foundry to a specific commit, hoping that now we are on the same commit it will resolve things. 
Let me know, thanks!

**Comment by iconofsin** [comment]
```shell
Chisel-GPT % git pull 
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 802 bytes | 80.00 KiB/s, done.
From https://github.com/max-taylor/Chisel-GPT
   042b006..73d2983  master     -> origin/master
Updating 042b006..73d2983
Fast-forward
 Cargo.lock | 36 +++++++++++++++++++-----------------
 Cargo.toml | 10 +++++-----
 2 files changed, 24 insertions(+), 22 deletions(-)
Chisel-GPT % cargo run
    Updating git repository `https://github.com/foundry-rs/foundry.git`
error: no matching package named `chisel` found
location searched: https://github.com/foundry-rs/foundry.git?rev=8307d6dc09dbd99d64239b901413869dc33cfa3e#8307d6dc
required by package `chisel_gpt v0.1.0 (/Users/zerno/Downloads/Chisel-GPT)`
Chisel-GPT % 
```
🤷 
idk, perhaps worth trying the Docker route. Will attempt that later.

**Comment by max-taylor** [comment]
I just modified the dependency to use the package name:
`chisel = { package = "chisel", git = "https://github.com/foundry-rs/foundry.git", rev = "8307d6dc09dbd99d64239b901413869dc33cfa3e" }`
Hoping that helps!

If not perhaps try deleting the following folders: `~/.cargo/git` and `~/.cargo/registry`. Your .cargo directory may not be in that exact path so might need to look for it.

**Comment by iconofsin** [comment]
This works! Thank you.

**Comment by max-taylor** [comment]
Awesome! Glad to hear, thanks for working through this with me!
