### ISSUE TITLE
Unsure how to provide the environment variable

### ISSUE THREAD

**Issue by martiam** [max-taylor/Chisel-GPT#2]
Hello, I don't know much about Rust, and I seem unable to provide my OpenAI API key as the environment variable. Could you give me a step-by-step guide or link me to relevant materials? Thank you.

**Comment by martiam** [comment]
Never mind, figured it out, instead of just typing `cargo run`, one is supposed to add the environmental variable before it, like this:
`OPENAI_API_KEY=your_api_key_here cargo run`. I think it might be good to provide this for people who are not familiar with Rust or cli.

**Comment by max-taylor** [comment]
Hey there, sorry about that, there is mention of it in Readme but it probably be a bit clearer. 

I'll update the docs, thanks!
