### ISSUE TITLE
Unsupported EVM version error

### ISSUE THREAD

**Issue by kuririn1** [max-taylor/Chisel-GPT#3]
I'm getting this error when trying to run code inside the chisel from the repo (!chat command works well):

thread 'main' panicked at 'Unsupported EVM version', /Users/xyz/.cargo/git/checkouts/foundry-f7cca724e93059b0/8307d6d/cli/src/utils.rs:93:14

**Comment by max-taylor** [comment]
Hi there, can you also send through the code you're trying to run. You might be trying to target a different version of solidity than the one inside the runtime, which can cause issues with Chisel.

**Comment by max-taylor** [comment]
Going to close from inactivity, feel free to open again if the issue persists. Thanks!
